title: "Global Tech Blog"
email: contact@example.com
description: >-
  English content covering global tech trends and AI developments.
baseurl: "/global-tech-blog"
url: "https://toreta.uk"

# SEO & Permalinks (✅ 키워드 URL)
permalink: /:year/:month/:day/:title/
future: true

# Build settings
theme: null # We are using custom layouts now
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
